### ISSUE TITLE
release 3.2 seems broken 

### ISSUE THREAD

**Issue by georgejecook** [rokucommunity/roku-deploy#38] opened 2020-07-07 17:11 UTC
aside form other issues I get when using bsc, I can no longer install, either.. 

installing on device with args { host: '192.168.8.204',
  username: 'rokudev',
  password: 'aaaa',
  files: [ '*', '**/*', '!*.zip', '!**/*.zip' ],
  app_name: 'Smithsonian Channel/5.11',
  rootDir: 'build',
  rekeySignedPackage: null,
  outDir: 'out',
  outFile: 'roku-deploy',
  signingPassword: null,
  retainStagingFolder: true }
deploying to device
There was a problem while instlaling on the device SyntaxError: Unexpected token / in JSON at position 664
[12:06:53] 'deploy' errored after 8.87 ms
[12:06:53] SyntaxError: Unexpected token / in JSON at position 664
    at JSON.parse (<anonymous>)
    at RokuDeploy.getOptions (/home/george/hope/smc/pot-smithsonian-channel-roku-xm/node_modules/roku-deploy/src/RokuDeploy.ts:711:36)
    at RokuDeploy.<anonymous> (/home/george/hope/smc/pot-smithsonian-channel-roku-xm/node_modules/roku-deploy/src/RokuDeploy.ts:653:24)
    at step (/home/george/hope/smc/pot-smithsonian-channel-roku-xm/node_modules/roku-deploy/dist/RokuDeploy.js:44:23)
    at Object.next (/home/george/hope/smc/pot-smithsonian-channel-roku-xm/node_modules/roku-deploy/dist/RokuDeploy.js:25:53)
    at /home/george/hope/smc/pot-smithsonian-channel-roku-xm/node_modules/roku-deploy/dist/RokuDeploy.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/home/george/hope/smc/pot-smithsonian-channel-roku-xm/node_modules/roku-deploy/dist/RokuDeploy.js:15:12)
    at RokuDeploy.deploy (/home/george/hope/smc/pot-smithsonian-channel-roku-xm/node_modules/roku-deploy/dist/RokuDeploy.js:856:16)
    at /home/george/hope/smc/pot-smithsonian-channel-roku-xm/gulpfile.ts:176:22

**Comment by TwitchBronBron** [comment] 2020-07-08 03:06
This issue is caused by roku-deploy trying to load bsconfig.json files from your working directory, and that bsconfig.json file containing comments. When we enhanced roku-deploy, we forgot that bsconfig.json files supported comments. So, I will be pushing a new release of roku-deploy momentarily that adds support for jsonc for rokudeploy.json and bsconfig.json.

**Comment by TwitchBronBron** [comment] 2020-07-08 03:27
Fixed in v3.2.1

**Closed by TwitchBronBron** 2020-07-08 03:27 UTC
